### ISSUE TITLE
Cannot be compiled with rustc 1.56.0 (09c42c458 2021-10-18)

### ISSUE THREAD

**Issue by ababo** [sdd/kiddo_v1#9]
Trying your library as a drop-in replacement for `kdtree-rs` I get:

```
  Compiling kiddo v0.1.5
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/ababo/.cargo/registry/src/github.com-1ecc6299db9ec823/kiddo-0.1.5/src/lib.rs:1:1
  |
1 | #![feature(allocator_api)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/ababo/.cargo/registry/src/github.com-1ecc6299db9ec823/kiddo-0.1.5/src/lib.rs:2:1
  |
2 | #![feature(destructuring_assignment)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `kiddo` due to 2 previous errors
```

**Comment by sdd** [comment]
Hi Simon,

At the moment, you'll need to use Rust's nightly channel rather than stable in order to use Kiddo.

But, if you really need to use this on stable, I should be able to refactor to eliminate the need for `destructuring_assignment` fairly easily. 

As for the `allocator_api` feature, I'm not even sure what, if anything, is using that. I'll look into removing the need for that for you, as it looks like from the tracking issue for this feature that it won't get stabilized any time soon (https://github.com/rust-lang/rust/issues/32838)

**Comment by ababo** [comment]
Hi Scott,

It would be nice to have it compilable on stable. This should attract more users if so.

Thank you.

**Comment by sdd** [comment]
Hi @ababo 

Turns out the `allocator_api` feature was unused, and the `destructuring_assignment` was trivial to factor out. I fixed this in https://github.com/sdd/kiddo/pull/11, which has been published to Crates.io as version 0.1.6: https://crates.io/crates/kiddo/0.1.6

Hopefully this should work for you now on rust stable 1.56!
